CREATE DATABASE LAB_01;

USE LAB_01;

CREATE TABLE CLIENTE (
	ID INT PRIMARY KEY NOT NULL,
    NOME VARCHAR(50),
    SOBRENOME VARCHAR(50)
);

INSERT INTO CLIENTE (ID, NOME, SOBRENOME) VALUES (1, 'José', 'Silva');

SELECT * FROM CLIENTE;

INSERT INTO CLIENTE (ID, NOME, SOBRENOME) 
	VALUES
    (2, 'Maria', 'Alves'),
    (3, 'Cláudia', 'Soares'),
    (4, 'Pedro', 'Tomé'),
    (5, 'Lucas', 'Antunes');
    
SELECT * FROM CLIENTE;

UPDATE CLIENTE
	SET NOME = 'Selma', SOBRENOME = 'Silva'
	WHERE ID = 3;
    
SELECT * FROM CLIENTE;

DELETE
	FROM CLIENTE
    WHERE ID = 3;
    
SELECT * FROM CLIENTE;